### PR TITLE
Clean serializer and Fix transferable bug

### LINKED ISSUE #7: Clean Serializer

### PR DESCRIPTION
**Pull request by VSerain**

### CODE REVIEW

**Comment by VSerain** [comment]
Think update the version after merge

File: src/HermesSerializers/defautSerializer.js [hunk 1]
```diff
@@ -15,100 +12,98 @@ module.exports =  {
...
-                } else {
-                    for (let t = 0; t < typedArray.length; t++) {
-                        if (args[i] instanceof self[typedArray[t]]) {
-                            transferable.push(args[i].buffer);
-                            args[i] = "hermes__transferable__" + transferable.length - 1;
-                            break;
-                        }
-                    }
-                }
+            if (argument instanceof ImageData && "ImageData" in self) {
```
Comment (robincartier) [inline src/HermesSerializers/defautSerializer.js:45]: Can you explain the "ImageData" in self part ? 

Why only use it in this if ?

File: src/HermesSerializers/defautSerializer.js [hunk 2]
```diff
@@ -15,100 +12,98 @@ module.exports =  {
...
+                        width: argument.width,
+                    },
+                });
+                return acc;
+            }
 
-                serializedArgs.push({
-                    type: "arg",
-                    value: args[i],
+            if (argument && typeof argument === "object" && argument.constructor.name in self && typedArray.includes(argument.constructor.name)) {
```
Comment (robincartier) [inline src/HermesSerializers/defautSerializer.js:58]: could it be useful to test `argument.constructor` as well ?

File: README.md [hunk 3]
```diff
@@ -208,4 +208,7 @@ hermes.call("length", [new BABYLON.Vector2(2, 0)]).then(result => {
 ### Changelog
 
 * **v1.0.0:** Initial release
-* **v1.0.1:** Add latest file in npm
\ No newline at end of file
+* **v1.0.1:** Add latest file in npm
+* **v1.0.2:**
```
Comment (robincartier) [inline README.md]: You changed the version to 1.1.0 in package.json. You should update your changelog

File: src/HermesSerializers/defautSerializer.js (hunk 1 above)
Comment (VSerain) [reply src/HermesSerializers/defautSerializer.js:45]: ImageData is particular because he needs buffer and width,  when other transferable object just need buffer

File: src/HermesSerializers/defautSerializer.js (hunk 2 above)
Comment (VSerain) [reply src/HermesSerializers/defautSerializer.js:58]: It's not necessaries because all objects in JavaScript have an attribute constructor (We have checked type of argument is object)

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor

File: README.md (hunk 3 above)
Comment (VSerain) [reply README.md]: Oops it's an omission, i clean this

Comment (VSerain) [reply README.md]: Done

**Review by robincartier — APPROVED** [review]
